title: Portraits Block
hidden: false
order: 3
status: wip
context:
  portrait:
    items:
      - portrait_title: Hannah Walsh
        portrait_sub: Business, 2019
        portrait_link: https://www.youtube.com/embed/0qYT5NpqN24?html5=1&enablejsapi=1&showinfo=0
      - portrait_title: Brady Campbell
        portrait_sub: Accounting, 2019
        portrait_link: https://www.youtube.com/embed/r8hLAfVz3sM?html5=1&enablejsapi=1
      - portrait_title: Molly Hammer
        portrait_sub: Psychology, 2019
        portrait_link: https://www.youtube.com/embed/jDMEv7HSSv4?html5=1&enablejsapi=1
