label: UIOWA Logo
hidden: false
order: 6
status: wip
context:
    logo_path: ../../images/uiowa.svg#uiowa-logo
    logo_path_2: ../../images/uiowa-secondary.svg#logo
    logo_path_3: ../../images/uiowa-left-01.svg#logo
    logo_color: logo__icon--secondary
