title: News Block
hidden: false
order: 3
status: wip
context:
  news:
    items:
      - card_tag: News
        card_title: Dedicated to having an impact on human health
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: ../../images/feature1.jpg
        card_text: Molecular medicine PhD student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.
        card_date: June 14, 1984
      - card_tag: News
        card_title: Getting to know Iowa's fall 2018 graduates
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: ../../images/feature2.jpg
        card_text: Receiving a diploma signals both an ending and a beginning.
        card_date: June 14, 1984
      - card_tag: News
        card_title: Turning the tide for sick seals
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: ../../images/feature3.jpg
        card_text: As the attending veterinarian at a marine mammal hospital in Los Angeles, University of Iowa alumna Lauren Palmer aims to rehabilitate and release sick or injured animals—and to help educate people about the ocean’s ecosystem.
        card_date: June 14, 1984
      - card_tag: News
        card_title: Swinging for the fences in sports management
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: ../../images/feature4.jpg
        card_text: Jake Stone is heading to the Baltimore Orioles organization after graduation. He says this was made possible by taking advantage of the opportunities offered by the University of Iowa’s Sport and Recreation Management Program and his work with the Hawkeye baseball team.
        card_date: June 14, 1984


