label: UIOWA Bar
order: 8
status: wip
context:
    bg_color: uiowa-bar--primary
    site_type: uiowa-bar--standard
variants:
  - name: Secondary
    context:
      bg_color: uiowa-bar--secondary
      site_type: uiowa-bar--standard
  - name: Home Page A
    context:
      bg_color: uiowa-bar--primary
      site_type: uiowa-bar--home
  - name: Home Page B
    context:
      bg_color: uiowa-bar--primary-b
      site_type: uiowa-bar--home
  - name: Home Page C
    context:
      bg_color: uiowa-bar--primary-c
      site_type: uiowa-bar--home



