label: UIOWA Bar
order: 8
status: wip
context:
    bg_color: uiowa-bar--primary
    site_type: uiowa-bar--standard
variants:
  - name: Secondary
    context:
      bg_color: uiowa-bar--secondary
      site_type: uiowa-bar--standard
  - name: Home Page
    context:
      bg_color: uiowa-bar--primary
      site_type: uiowa-bar--home


