title: Bold Headline
order: 2
status: wip
collated: true
context:
    bold_headline: Bold Hawkeye Headline Here
    headline_type: bold-headline--positive
    background_type: bg-type--light
variants:
  - name: Bold Headline Reversed
    context:
      bold_headline: Bold Hawkeye Headline Reversed
      headline_type: bold-headline--negative
      background_type: bg-type--dark

