title: Button
hidden: false
order: 2
status: wip
collated: false
context:
  button:
    text: More News
    type: bttn--tertiary
    link: https://www.example.com
    background_type: bg-type--dark
variants:
  - name: button--gold
    context:
      button:
        text: More News
        type: bttn--primary
        link: https://www.example.com
        background_type: bg-type--dark
  - name: button--black-bg
    context:
      button:
        text: More News
        type: bttn--secondary
        link: https://www.example.com
        background_type: bg-type--light
  - name: button--outline
    context:
      button:
        text: More News
        type: bttn--outline bttn--secondary__light
        background_type: bg-type--dark
        icon: yes
  - name: button--full-regular
    context:
      button:
        text: More News
        type: bttn--full bttn--tertiary
        background_type: bg-type--dark
  - name: button--full-gold
    context:
      button:
        text: More News
        type: bttn--full bttn--primary
        background_type: bg-type--dark
  - name: button--full-black-gold
    context:
      button:
        text: More News
        type: bttn--full bttn--secondary
        background_type: bg-type--light
  - name: button--full-outline
    context:
      button:
        text: More News
        type: bttn--full bttn--outline bttn--secondary__light
        background_type: bg-type--dark
        icon: yes
  - name: button--full-outline-reversed
    context:
      button:
        text: More News
        type: bttn--full bttn--outline bttn--tertiary
        background_type: bg-type--light
        icon: yes
