title: Site Name
hidden: false
order: 9
status: wip
context:
    footer_logo: ../../images/dome.png
    link_bttn:
      items:
      - link_bttn_title: Request Info
        link_bttn_url: https://example.com
        link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
        link_bttn_icon: fas fa-info-circle
      - link_bttn_title:  Visit
        link_bttn_url: https://example.com
        link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
        link_bttn_icon: fas fa-map-marker-alt
      - link_bttn_title: Apply
        link_bttn_url: https://example.com
        link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
        link_bttn_icon: fas fa-pencil-alt
      - link_bttn_title: Jobs
        link_bttn_url: https://example.com
        link_bttn_class: bttn bttn--full bttn--outline bttn--secondary__light
        link_bttn_icon: fas fa-folder
    link_icon:
      items:
      - link_icon_title: Facebook
        link_icon_url: https://example.com
        link_icon_class: fab fa-facebook-square
      - link_icon_title:  Twitter
        link_icon_url: https://example.com
        link_icon_class: fab fa-twitter-square
        link_bttn_icon: fab fa-twitter-square
      - link_icon_title: Instagram
        link_icon_url: https://example.com
        link_icon_class: fab fa-instagram
      - link_icon_title: Snapchat
        link_icon_url: https://example.com
        link_icon_class: fab fa-snapchat
      - link_icon_title: Youtube
        link_icon_url: https://example.com
        link_icon_class: fab fa-youtube
    links_nav:
      links:
      - link_nav_text: Current section
        links:
        - link_nav_text: Navigation link 1
          link_nav_url: '#'
        - link_nav_text: Navigation link 2
          link_nav_url: '#'
        - link_nav_text: Navigation link 3
          link_nav_url: '#'
        - link_nav_text: Navigation link 4
          link_nav_url: '#'

variants:
  - name: links-bttn
    label: Footer Links Bttn
    hidden: true
  - name: links-icon
    label: Footer Links Icon
    hidden: true
  - name: links-nav
    label: Footer Links Nav
    hidden: true
