title: Site Name
label: Layouts
hidden: false
order: 10
status: wip
context:
  site_name: Department of College
  site_slogan: College Name
  site_front: /
  site_title: Home Page
  header_alignment: site-header__default
  menu_type: superfish
  site_type: primary
  header_type: site-header--secondary
  nav_type: navbar--secondary
  button:
    text: Call to Action
    link: https://example2.com
    type: bttn--basic bttn--tertiary
  feature_columns: feature__three-col
  feature_type: image
  feature:
    items:
      - feature_title: Having an Impact
        feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
        feature_banner_image: ../../images/feature1.jpg
        feature_link: https://example.com
      - feature_title: 2019 Graduates
        feature_sub: Receiving a diploma signals both an ending and a beginning
        feature_banner_image: ../../images/feature2.jpg
        feature_link: https://example.com
      - feature_title: Turning the Tide
        feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
        feature_banner_image: ../../images/feature3.jpg
        feature_link: https://example.com
  icons:
    items:
      - icon_title: Areas of Study
        icon_link: https://example.com
        icon_image: ../../images/stack-of-books.svg#icon
      - icon_title: Cost and Aid
        icon_link: https://example.com
        icon_image: ../../images/scholarship.svg#icon
      - icon_title: Visit Campus
        icon_link: https://example.com
        icon_image: ../../images/map-pin.svg#icon
      - icon_title: Apply Now
        icon_link: https://example.com
        icon_image: ../../images/paper.svg#icon
  stat:
    items:
      - stat_title: '15:1'
        stat_summary: 'student-to-faculty ratio'
        stat_image: ../../images/feature1.jpg
      - stat_title: '78%'
        stat_summary: 'of classes have fewer than 30 students'
        stat_image: ../../images/feature2.jpg
      - stat_title: '14'
        stat_summary: 'consecutive years named a "Best Buy" by Fiske Guide to Colleges'
        stat_image: ../../images/feature3.jpg
      - stat_title: '5,000'
        stat_summary: 'courses offered every year'
        stat_image: '../../images/feature1.jpg'
  news:
    items:
      - card_tag: News
        card_title: Dedicated to having an impact on human health
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: ../../images/feature1.jpg
        card_text: Molecular medicine PhD student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.
        card_date: June 14, 1984
      - card_tag: News
        card_title: Getting to know Iowa's fall 2018 graduates
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: ../../images/feature2.jpg
        card_text: Receiving a diploma signals both an ending and a beginning.
        card_date: June 14, 1984
      - card_tag: News
        card_title: Turning the tide for sick seals
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: ../../images/feature3.jpg
        card_text: As the attending veterinarian at a marine mammal hospital in Los Angeles, University of Iowa alumna Lauren Palmer aims to rehabilitate and release sick or injured animals—and to help educate people about the ocean’s ecosystem.
        card_date: June 14, 1984
      - card_tag: News
        card_title: Swinging for the fences in sports management
        card_link_title: Read Article
        card_link_url: https://example.com
        card_image: ../../images/feature4.jpg
        card_text: Jake Stone is heading to the Baltimore Orioles organization after graduation. He says this was made possible by taking advantage of the opportunities offered by the University of Iowa’s Sport and Recreation Management Program and his work with the Hawkeye baseball team.
        card_date: June 14, 1984
  portrait:
    items:
      - portrait_title: Hannah Walsh
        portrait_sub: Business, 2019
        portrait_link: https://www.youtube.com/embed/0qYT5NpqN24?html5=1&enablejsapi=1&showinfo=0
      - portrait_title: Brady Campbell
        portrait_sub: Accounting, 2019
        portrait_link: https://www.youtube.com/embed/r8hLAfVz3sM?html5=1&enablejsapi=1
      - portrait_title: Molly Hammer
        portrait_sub: Psychology, 2019
        portrait_link: https://www.youtube.com/embed/jDMEv7HSSv4?html5=1&enablejsapi=1
variants:
  - name: default
    label: Default Secondary Superfish
  - name: Default Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__default
      menu_type: superfish
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
      feature_columns: feature__two-col
      feature_type: image
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature2.jpg
            feature_link: https://example.com
  - name: Default Tertiary Superfish
    context:
      header_alignment: site-header__default
      menu_type: superfish
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Aligned Left Secondary Superfish
    context:
      site_slogan:
      header_alignment: site-header__left
      site_type: primary
      header_type: site-header--secondary
      nav_type: navbar--secondary
  - name: Aligned Left Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__left
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
  - name: Aligned Left Tertiary Superfish
    context:
      header_alignment: site-header__left
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Aligned Center Secondary Superfish
    context:
      header_alignment: site-header__center
      site_type: primary
  - name: Aligned Center Primary Superfish
    hidden: true
    context:
      header_alignment: site-header__center
      site_type: secondary
      header_type: site-header--primary
      nav_type: navbar--primary
  - name: Aligned Center Tertiary Superfish
    context:
      header_alignment: site-header__center
      site_type: secondary
      header_type: site-header--tertiary
      nav_type: navbar--primary
  - name: Default Main Menu
    context:
      header_alignment: site-header__default
      menu_type: main
      site_type: primary
  - name: Aligned Left Main Menu
    context:
      header_alignment: site-header__left
      menu_type: main
      site_type: primary
  - name: Aligned Center Main Menu
    context:
      header_alignment: site-header__center
      menu_type: main
      site_type: primary
  - name: UIOWA Home Page Mega Menu
    context:
      header_alignment: site-header__center
      menu_type: mega
      site_type: tertiary
      header_type:
      nav_type: navbar--tertiary


