title: Feature Block
hidden: false
order: 3
status: wip
context:
  feature_type: image
  feature:
    items:
      - feature_title: Having an Impact
        feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
        feature_banner_image: ../../images/feature1.jpg
        feature_link: https://example.com
      - feature_title: 2019 Graduates
        feature_sub: Receiving a diploma signals both an ending and a beginning
        feature_banner_image: ../../images/feature2.jpg
        feature_link: https://example.com
      - feature_title: Turning the Tide
        feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
        feature_banner_image: ../../images/feature3.jpg
        feature_link: https://example.com
variants:
  - name: Feature Block Video
    context:
      feature_type: video
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature2.jpg
            feature_link: https://example.com
          - feature_title: Turning the Tide
            feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
            feature_banner_image: ../../images/feature3.jpg
            feature_link: https://example.com
  - name: Feature Block Image Stack
    context:
      feature_type: image-stack
      feature:
        items:
          - feature_title: Having an Impact
            feature_sub: Jordan Kohlmeyer is researching new therapies for tumors
            feature_banner_image: ../../images/feature1.jpg
            feature_link: https://example.com
          - feature_title: 2019 Graduates
            feature_sub: Receiving a diploma signals both an ending and a beginning
            feature_banner_image: ../../images/feature2.jpg
            feature_link: https://example.com
          - feature_title: Turning the Tide
            feature_sub: Alumna Lauren Palmer aims to rehabilitate animals
            feature_banner_image: ../../images/feature3.jpg
            feature_link: https://example.com
