title: Statistics Block
hidden: false
order: 3
status: wip
context:
  stat:
    items:
      - stat_title: '15:1'
        stat_summary: 'student-to-faculty ratio'
        stat_image: ../../images/feature1.jpg
      - stat_title: '78%'
        stat_summary: 'of classes have fewer than 30 students'
        stat_image: ../../images/feature2.jpg
      - stat_title: '14'
        stat_summary: 'consecutive years named a "Best Buy" by Fiske Guide to Colleges'
        stat_image: ../../images/feature3.jpg
      - stat_title: '5,000'
        stat_summary: 'courses offered every year'
        stat_image: '../../images/feature1.jpg'

variants:
  - name: default
    label: Statistics Block 3
    status: null
    context:
      stat_items: '3'

  - name: More
    label: Statistics Block 4
    hidden: false
    context:
      stat_items: '4'

  - name: advanced
    label: Stat Block Advanced
    hidden: true

  - name: basic
    label: Stat Block Basic
    hidden: true
