title: Statistics Block
hidden: false
order: 3
status: wip
context:
  stat_items: '3'
  stat:
    items:
      - stat_title: '15:1'
        stat_summary: 'student-to-faculty ratio'
        stat_image: ../../images/feature1.jpg
      - stat_title: '78%'
        stat_summary: 'of classes have fewer than 30 students'
        stat_image: ../../images/feature2.jpg
      - stat_title: '14'
        stat_summary: 'consecutive years named a "Best Buy" by Fiske Guide to Colleges'
        stat_image: ../../images/feature3.jpg
      - stat_title: '5,000'
        stat_summary: 'courses offered every year'
        stat_image: '../../images/feature1.jpg'

variants:
  - name: Statistics Block Two Items
    context:
      stat_items: '2'
  - name: Statistics Block Four Items
    context:
      stat_items: '4'
