title: Headline
order: 2
status: wip
collated: true
context:
    headline_level: h2
    headline_title: Bold Hawkeye Headline Here
    headline_type: bold-headline bold-headline--positive
    background_type: bg-type--light
variants:
  - name: Bold Headline Reversed
    hidden: true
    context:
      headline_level: h2
      headline_title: Bold Hawkeye Headline Reversed
      headline_type: bold-headline bold-headline--negative
      background_type: bg-type--dark

